services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        API_URL: https://devils-codex.azurewebsites.net
    ports:
      - "80:80"

  backend:
    container_name: backend
    build:
      context: ./backend
