services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        API_URL: https://${WEBAPP_NAME}.azurewebsites.net
    image: ${ACR_NAME}.azurecr.io/${WEBAPP_NAME}-frontend:latest
    ports:
      - "80:80"

  backend:
    container_name: backend
    build:
      context: ./backend
    image: ${ACR_NAME}.azurecr.io/${WEBAPP_NAME}-backend:latest
